# theme: architect #minima
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Paducah KY Stake Leadership Blog
author: Paducak KY Stake
description: The leadership blog for the Paducah KY Stake of The Church Of Jesus Christ Of Latter-day Saints. 
  This is not an official site of The Church Of Jesus Christ Of Latter-day Saints. 